# -*- coding: utf-8 -*-
"""4_080.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oo2V9fLa1LZevTOHiNVkPgiQ3_3LpUK2
"""

print("'080 Nishita Giri")
from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.hazmat.primitives import hashes
from cryptography.exceptions import InvalidSignature

private_key = rsa.generate_private_key(
    public_exponent=65537,
    key_size=2048
)

public_key = private_key.public_key()

print("RSA Keys Generated Successfully!")

message = input("\nEnter message to sign: ").encode()

print("\nOriginal Message:")
print(message.decode())

signature = private_key.sign(
    message,
    padding.PSS(
        mgf=padding.MGF1(hashes.SHA256()),
        salt_length=padding.PSS.MAX_LENGTH
    ),
    hashes.SHA256()
)

print("\nDigital Signature Created Successfully!")
print("Signature length:", len(signature), "bytes")

try:
    public_key.verify(
        signature,
        message,
        padding.PSS(
            mgf=padding.MGF1(hashes.SHA256()),
            salt_length=padding.PSS.MAX_LENGTH
        ),
        hashes.SHA256()
    )

    print("\nSignature Verification: SUCCESS")
    print("Message is authentic and has not been modified.")

except InvalidSignature:
    print("\nSignature Verification: FAILED")

modified_message = input("\nEnter message to verify: ").encode()

print("\nMessage for Verification:")
print(modified_message.decode())

try:
    public_key.verify(
        signature,
        modified_message,
        padding.PSS(
            mgf=padding.MGF1(hashes.SHA256()),
            salt_length=padding.PSS.MAX_LENGTH
        ),
        hashes.SHA256()
    )

    print("\nVerification: SUCCESS")
    print("Message is authentic and has not been modified.")

except InvalidSignature:
    print("\nVerification: FAILED")
    print("Integrity violation detected!")

print("'080 Nishita Giri")
from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.hazmat.primitives import hashes
from cryptography.exceptions import InvalidSignature

private_key = rsa.generate_private_key(
    public_exponent=65537,
    key_size=2048
)

public_key = private_key.public_key()

print("RSA Keys Generated Successfully!")

message = input("\nEnter message to sign: ").encode()

print("\nOriginal Message:")
print(message.decode())

signature = private_key.sign(
    message,
    padding.PSS(
        mgf=padding.MGF1(hashes.SHA256()),
        salt_length=padding.PSS.MAX_LENGTH
    ),
    hashes.SHA256()
)

print("\nDigital Signature Created Successfully!")
print("Signature length:", len(signature), "bytes")

try:
    public_key.verify(
        signature,
        message,
        padding.PSS(
            mgf=padding.MGF1(hashes.SHA256()),
            salt_length=padding.PSS.MAX_LENGTH
        ),
        hashes.SHA256()
    )

    print("\nSignature Verification: SUCCESS")
    print("Message is authentic and has not been modified.")

except InvalidSignature:
    print("\nSignature Verification: FAILED")

modified_message = input("\nEnter message to verify: ").encode()

print("\nMessage for Verification:")
print(modified_message.decode())

try:
    public_key.verify(
        signature,
        modified_message,
        padding.PSS(
            mgf=padding.MGF1(hashes.SHA256()),
            salt_length=padding.PSS.MAX_LENGTH
        ),
        hashes.SHA256()
    )

    print("\nVerification: SUCCESS")
    print("Message is authentic and has not been modified.")

except InvalidSignature:
    print("\nVerification: FAILED")
    print("Integrity violation detected!")